[tool.poetry]
name = "brazilian_money_format"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
homepage = "https://github.com"

[tool.poetry.dependencies]
#python = "^3.8"
#pandas = "^1.1.1"
#pandas = { git = "https://github.com/pandas-dev/pandas.git", tag = "v1.1.2" }
#numpy = { git = "https://github.com/numpy/numpy.git", tag = "v1.20.1 " }
#numpy = "1.16.0"
python = "^3.8"
playwright = "^0.171.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
brazilian_money_format = "brazilian_money_format:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
