[tool.poetry]
name = "minimal_python_builtin_script"
version = "3.1.2"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
homepage = "https://github.com"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
minimal_python_builtin_script = "minimal_python_builtin_script:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
