[tool.poetry]
name = "brazilian_money_format"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
homepage = "https://github.com"

[tool.poetry.dependencies]
python = "^3.8"
playwright = "^0.171.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
